/** Temporary balance values, in simulation seconds. Hunger: 0 full, 100 empty. */
export const BALANCE = Object.freeze({
  villageHouses: 5,
  villageHouseLimit: 15,
  villageRadius: 14,
  kingdomVillages: 2,
  kingdomVillageLimit: 5,
  kingdomPopulation: 16,
  kingdomRadius: 60,
  kingdomInitialRadius: 20,
  kingdomExpansionYears: 5,
  kingdomSingleVillageHouses: 10,
  farmWorkSeconds: 5,
  lifespanMin: 75,
  lifespanMax: 95,
  adultAge: 18,
  birthMaxAge: 45,
  birthInterval: 540,
  marriageRadius: 30,
  populationLimit: 500,
  houseWood: 3,
  houseStone: 2,
  gatherSeconds: 2,
  buildSeconds: 5,
  woodRegrowSeconds: 45,
  secondsPerYear: 720,
  startingHunger: 25,
  hungerPerSecond: 0.7,
  seekFoodAt: 45,
  starvationDamage: 4,
  mealRecovery: 40,
  mealSeconds: 2,
  healthRecovery: 2,
  walkingSpeed: 1.8,
  foodRegrowSeconds: 40,
  foodCapacity: 3,
  foodDensity: 0.02,
});
