/** Temporary balance values, in simulation seconds. Hunger: 0 full, 100 empty. */
export const BALANCE = Object.freeze({
  lifespanMin: 75,
  lifespanMax: 95,
  adultAge: 18,
  birthMaxAge: 45,
  birthInterval: 60,
  marriageRadius: 30,
  populationLimit: 500,
  houseWood: 3,
  houseStone: 2,
  gatherSeconds: 2,
  buildSeconds: 5,
  woodRegrowSeconds: 45,
  secondsPerYear: 60,
  startingHunger: 25,
  hungerPerSecond: 0.7,
  seekFoodAt: 45,
  starvationDamage: 4,
  mealRecovery: 40,
  mealSeconds: 2,
  healthRecovery: 2,
  walkingSpeed: 1.8,
  foodRegrowSeconds: 40,
  foodCapacity: 3,
  foodDensity: 0.008,
});
